# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Export + Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build
    - run: npm run export
    - run: tree -ah out
    - name: Upload exported static site
      uses: actions/upload-artifact@v2
      with:
        name: export
        path: out

  deploy:

    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - name: Download exported static site
      uses: actions/download-artifact@v2
      with:
        name: export
        path: out
    - run: tree -ah
    - run: aws --version
    - name: aws s3 sync
      env:
        AWS_DEFAULT_REGION: eu-central-1
        AWS_ACCESS_KEY_ID: ${{ DEPLOY_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ DEPLOY_AWS_SECRET_ACCESS_KEY }}
      working-directory: out
      run: aws s3 sync . s3://messa-websites/petr.messner.cz/
